on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Node 20.9.0
      uses: actions/setup-node@v1
      with:
        node-version: 20.9.0

    - name: Install and build
      run: |
        npm i
        npm run build
    - name: Run tests
      run: |
        npm run test -- --watch=false --browsers=ChromeHeadless